[2021-09-07 13:27:44,029] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: daily_update_covid_tables.create_database 2021-09-06T13:01:00+00:00 [queued]>
[2021-09-07 13:27:44,033] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: daily_update_covid_tables.create_database 2021-09-06T13:01:00+00:00 [queued]>
[2021-09-07 13:27:44,033] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 13:27:44,033] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-09-07 13:27:44,033] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 13:27:44,039] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_database> on 2021-09-06T13:01:00+00:00
[2021-09-07 13:27:44,041] {standard_task_runner.py:52} INFO - Started process 50 to run task
[2021-09-07 13:27:44,043] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'daily_update_covid_tables', 'create_database', '2021-09-06T13:01:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpn7z4u04g', '--error-file', '/tmp/tmpg8w42osh']
[2021-09-07 13:27:44,043] {standard_task_runner.py:77} INFO - Job 17: Subtask create_database
[2021-09-07 13:27:44,060] {logging_mixin.py:109} INFO - Running <TaskInstance: daily_update_covid_tables.create_database 2021-09-06T13:01:00+00:00 [running]> on host 42585af7096a
[2021-09-07 13:27:44,080] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_update_covid_tables
AIRFLOW_CTX_TASK_ID=create_database
AIRFLOW_CTX_EXECUTION_DATE=2021-09-06T13:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-06T13:01:00+00:00
[2021-09-07 13:27:44,087] {python.py:151} INFO - Done. Returned value was: None
[2021-09-07 13:27:44,091] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=daily_update_covid_tables, task_id=create_database, execution_date=20210906T130100, start_date=20210907T132744, end_date=20210907T132744
[2021-09-07 13:27:44,134] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-07 13:27:44,146] {local_task_job.py:261} INFO - 2 downstream tasks scheduled from follow-on schedule check
