[2021-09-06 14:26:32,230] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dag_teste.create_database 2021-09-05T13:01:00+00:00 [queued]>
[2021-09-06 14:26:32,237] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dag_teste.create_database 2021-09-05T13:01:00+00:00 [queued]>
[2021-09-06 14:26:32,237] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-06 14:26:32,237] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-09-06 14:26:32,237] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-06 14:26:32,241] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_database> on 2021-09-05T13:01:00+00:00
[2021-09-06 14:26:32,244] {standard_task_runner.py:52} INFO - Started process 379 to run task
[2021-09-06 14:26:32,246] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_teste', 'create_database', '2021-09-05T13:01:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_6k47va3', '--error-file', '/tmp/tmpj6687ps1']
[2021-09-06 14:26:32,246] {standard_task_runner.py:77} INFO - Job 4: Subtask create_database
[2021-09-06 14:26:32,265] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_teste.create_database 2021-09-05T13:01:00+00:00 [running]> on host 5d69a7ea1639
[2021-09-06 14:26:32,289] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_teste
AIRFLOW_CTX_TASK_ID=create_database
AIRFLOW_CTX_EXECUTION_DATE=2021-09-05T13:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-05T13:01:00+00:00
[2021-09-06 14:26:32,290] {python.py:151} INFO - Done. Returned value was: None
[2021-09-06 14:26:32,295] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=dag_teste, task_id=create_database, execution_date=20210905T130100, start_date=20210906T142632, end_date=20210906T142632
[2021-09-06 14:26:32,337] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-06 14:26:32,350] {local_task_job.py:261} INFO - 2 downstream tasks scheduled from follow-on schedule check
